apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  # username: root (base64 encoded)
  username: cm9vdA==
  # password: password123 (base64 encoded)
  password: cGFzc3dvcmQxMjM= 