apiVersion: v1
kind: Service
metadata:
  name: node-web-service
  labels:
    app: node-web-app
spec:
  type: NodePort
  selector:
    app: node-web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3002
      nodePort: 30036
      name: http
